version: "3"


services:


  n8n:

    image: docker.n8n.io/n8nio/n8n:latest

    restart: always

    ports:

      - "127.0.0.1:5678:5678"

    environment:

      - N8N_BASIC_AUTH_ACTIVE=true

      - N8N_BASIC_AUTH_USER = ${N8N_BASIC_AUTH_USER}

      - N8N_BASIC_AUTH_PASSWORD = ${N8N_BASIC_AUTH_PASSWORD}

      - N8N_HOST=${DOMAIN_NAME}

      - N8N_PORT=5678

      - N8N_PROTOCOL=https

      - NODE_ENV=production

      - WEBHOOK_URL=https://${DOMAIN_NAME}/

      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}

    volumes:

      - ${DATA_FOLDER}/.n8n:/home/node/.n8n


 
